name: example_flutter
description: An example project for flutter-desktop-embedding.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_staggered_grid_view: ^0.2.7

  # Desktop embedder plugins.
  # Note: In an actual project, these paths would include the
  # path from your application to the flutter_desktop_embedding
  # checkout.
  color_panel:
    path: ../plugins/color_panel
  file_chooser:
    path: ../plugins/file_chooser
  menubar:
    path: ../plugins/menubar

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/profile.jpg
    - images/pancake.jpg
    - images/list1.jpg
    - images/list2.jpg
    - images/list3.jpg
    - images/list4.jpg
    - images/list5.jpg
    - images/list6.jpg


  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Black.ttf
          weight: 900
